/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;
import business.EMA;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import data.EMADB;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author User
 */
public class EmployeeUI extends javax.swing.JFrame {
    private EMA bk;
    private DefaultTableModel tblModel;
    private ArrayList<EMA> emaList;
    private EMADB bDB;
    /**
     * Creates new form EmployeeUI
     */
    public EmployeeUI() {
        initComponents();
        
        
        String filePath = "C:\\EMSS\\EMS.txt";
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)tblema.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++) {
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
                        
            }
                  
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    
        
        setLocationRelativeTo(this);
        tblModel=new DefaultTableModel();
        tblema.setModel(tblModel);
        tblModel.addColumn("Empolyee ID");
        tblModel.addColumn("First Name");
        tblModel.addColumn("Last Name");
        tblModel.addColumn("Department");
        tblModel.addColumn("Designation");
        tblModel.addColumn("Gender");
        tblModel.addColumn("Status");
        tblModel.addColumn("Contact No");
        
        emaList=new ArrayList<>();
        bDB=new EMADB();
    }
    
    

    private boolean checkVal(){
        if(txtemployeeid.getText().equals("")){
            JOptionPane.showMessageDialog(this, "EMA Id cannot be blank");
            return false;
        }
    
        if(txtfirstname1.getText().equals("")){
             JOptionPane.showMessageDialog(this, "First name cannot be blank");
             return false;
        }
        
        if(txtlastname.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Last Name cannot be blank");
             return false;
        }
        
        if(txtdesignation.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this, "department cannot be blank");
             return false;
        }

        if(txtdesignation.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this, "designation cannot be blank");
             return false;
        }

        if(txtgender.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this, "Gender cannot be blank");
             return false;
        }

        if(txtdesignation.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this, "status cannot be blank");
             return false;
        }

        if(txtcontactno.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Contact no cannot be blank");
             return false;
        }
        
        return true;

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblema = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtdesignation = new javax.swing.JComboBox<>();
        txtgender = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcontactno = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnewdepartment = new javax.swing.JTextField();
        txtfirstname1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtemployeeid = new javax.swing.JTextField();
        txtstatus1 = new javax.swing.JComboBox<>();
        btnAdd1 = new javax.swing.JButton();
        txtdepartment1 = new javax.swing.JComboBox<>();
        txtnewdesignation2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("Department :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblema.setBackground(new java.awt.Color(204, 204, 255));
        tblema.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblemaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblema);
        if (tblema.getColumnModel().getColumnCount() > 0) {
            tblema.getColumnModel().getColumn(1).setResizable(false);
            tblema.getColumnModel().getColumn(2).setResizable(false);
            tblema.getColumnModel().getColumn(3).setResizable(false);
            tblema.getColumnModel().getColumn(4).setResizable(false);
            tblema.getColumnModel().getColumn(5).setResizable(false);
            tblema.getColumnModel().getColumn(6).setResizable(false);
            tblema.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 670, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText(" Employee Panel");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 320, -1));

        txtdesignation.setBackground(new java.awt.Color(153, 153, 255));
        txtdesignation.setForeground(new java.awt.Color(255, 255, 255));
        txtdesignation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", " " }));
        txtdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesignationActionPerformed(evt);
            }
        });
        jPanel1.add(txtdesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 200, 30));

        txtgender.setBackground(new java.awt.Color(153, 153, 255));
        txtgender.setForeground(new java.awt.Color(255, 255, 255));
        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        jPanel1.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 130, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 51, 51));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 51, 51));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        btnback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 51, 51));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jLabel11.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Last Name :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txtlastname.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, 30));

        jLabel10.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("First Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel13.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText("Designation :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("Gender :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("Status :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jLabel16.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText("Contact No :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtcontactno.setBackground(new java.awt.Color(153, 153, 255));
        txtcontactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 200, 30));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 51, 51));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel18.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText("Department :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Empolyee ID :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Empolyee Information");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 18, -1, -1));

        txtnewdepartment.setBackground(new java.awt.Color(153, 153, 255));
        txtnewdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewdepartment1ActionPerformed(evt);
            }
        });
        txtnewdepartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnewdepartment1KeyPressed(evt);
            }
        });
        jPanel1.add(txtnewdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 30));

        txtfirstname1.setBackground(new java.awt.Color(153, 153, 255));
        txtfirstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstname1ActionPerformed(evt);
            }
        });
        txtfirstname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfirstname1KeyPressed(evt);
            }
        });
        jPanel1.add(txtfirstname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 30));

        jLabel19.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText("New Department :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 BT", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 255));
        jLabel20.setText("New Designation :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        txtemployeeid.setBackground(new java.awt.Color(153, 153, 255));
        txtemployeeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemployeeidActionPerformed(evt);
            }
        });
        txtemployeeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemployeeidKeyPressed(evt);
            }
        });
        jPanel1.add(txtemployeeid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 30));

        txtstatus1.setBackground(new java.awt.Color(153, 153, 255));
        txtstatus1.setForeground(new java.awt.Color(255, 255, 255));
        txtstatus1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Active", "In-Active" }));
        txtstatus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatus1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtstatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 140, 30));

        btnAdd1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(0, 51, 51));
        btnAdd1.setText("Add");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        txtdepartment1.setBackground(new java.awt.Color(153, 153, 255));
        txtdepartment1.setForeground(new java.awt.Color(255, 255, 255));
        txtdepartment1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", " " }));
        txtdepartment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepartment1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtdepartment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, 30));

        txtnewdesignation2.setBackground(new java.awt.Color(153, 153, 255));
        txtnewdesignation2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewdesignation21ActionPerformed(evt);
            }
        });
        txtnewdesignation2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnewdesignation21KeyPressed(evt);
            }
        });
        jPanel1.add(txtnewdesignation2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 200, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tblModel =(DefaultTableModel) tblema.getModel();
        if(tblema.getSelectedRowCount()== 1){
            
            String empolyeeid = txtemployeeid.getText();
            String fristname = txtfirstname1.getText();
            String lastname = txtlastname.getText();
            String department =(String) txtdepartment1.getSelectedItem();
            String designation =(String) txtdesignation.getSelectedItem();
            String gender = (String) txtgender.getSelectedItem();
            String status = (String) txtstatus1.getSelectedItem();
            String contactno =  txtcontactno.getText();
            
            
            tblModel.setValueAt(empolyeeid,tblema.getSelectedRow(),0);
            tblModel.setValueAt(fristname,tblema.getSelectedRow(),1);
            tblModel.setValueAt(lastname,tblema.getSelectedRow(),2);
            tblModel.setValueAt(department,tblema.getSelectedRow(),3);
            tblModel.setValueAt(designation,tblema.getSelectedRow(),4);
            tblModel.setValueAt(gender,tblema.getSelectedRow(),5);
            tblModel.setValueAt(status ,tblema.getSelectedRow(),6);
            tblModel.setValueAt(contactno,tblema.getSelectedRow(),7);
            
            JOptionPane.showMessageDialog(this,"Update Successfully.");
            
        }else{
            if(tblema.getRowCount()==0){
        
        
                JOptionPane.showMessageDialog(this,"Table is empty");
            
            }else{
                    
                JOptionPane.showMessageDialog(this,"Please select Single Row");
                    
            }
       
        }

        String filePath = "C:\\EMSS\\EMS.txt";
        File file = new File(filePath);
                
        try {
            
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0; i < tblema.getRowCount(); i++ ){
                for (int j=0; j < tblema.getColumnCount(); j++){
                    bw.write(tblema.getValueAt(i,j).toString()+" ");
                        
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tblModel =(DefaultTableModel) tblema.getModel();
        
        if(tblema.getSelectedRowCount()==1){
            tblModel.removeRow(tblema.getSelectedRow());
            
            
        }else{
            if(tblema.getRowCount()==0){
                
                JOptionPane.showMessageDialog(this,"Table is Empty.");
                
            }else{
                JOptionPane.showMessageDialog(this,"Please select Single Row for Delete");
            }
        }
        
        String filePath = "C:\\EMSS\\EMS.txt";
        File file = new File(filePath);
                
        try {
            
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0; i < tblema.getRowCount(); i++ ){
                for (int j=0; j < tblema.getColumnCount(); j++){
                    bw.write(tblema.getValueAt(i,j).toString()+" ");
                        
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }

            
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
                    SearchUI sUI=new SearchUI();
                    sUI.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        
                    LoginUI LUI=new LoginUI();
                    LUI.setVisible(true);
                    this.setVisible(false);
        
        
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        
        if (txtemployeeid.getText().equals("")||txtfirstname1.getText().equals("")||txtlastname.getText().equals("")||txtdepartment1.getSelectedItem().toString().equals("")||txtdesignation.getSelectedItem().toString().equals("")||txtgender.getSelectedItem().toString().equals("")||txtstatus1.getSelectedItem().toString().equals("")||txtcontactno.getText().equals("")){

           
            
            JOptionPane.showMessageDialog(this,"Please Enter All Data... !");
        }else{
            String data[] = {txtemployeeid.getText(),txtfirstname1.getText(),txtlastname.getText(),txtdepartment1.getSelectedItem().toString(),txtdesignation.getSelectedItem().toString(),txtgender.getSelectedItem().toString(),txtstatus1.getSelectedItem().toString(),txtcontactno.getText()};

            DefaultTableModel tblModel = (DefaultTableModel)tblema.getModel();

            tblModel.addRow(data);

            JOptionPane.showMessageDialog(this, "Add Data Successfully...1");

            txtemployeeid.setText("");
            txtfirstname1.setText("");
            txtlastname.setText("");
            txtdepartment1.setSelectedItem("");
            txtdesignation.setSelectedItem("");
            txtgender.setSelectedItem("");
            txtstatus1.setSelectedItem("");
            txtcontactno.setText("");
        }
        
        String filePath = "C:\\EMSS\\EMS.txt";
        File file = new File(filePath);
                
        try {
            
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i=0; i < tblema.getRowCount(); i++ ){
                for (int j=0; j < tblema.getColumnCount(); j++){
                    bw.write(tblema.getValueAt(i,j).toString()+" ");
                        
                }
                bw.newLine();
            }
            
            bw.close();
            fw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(EmployeeUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtcontactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactnoActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void tblemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblemaMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tblModel = (DefaultTableModel)tblema.getModel();
        
            String tblempolyeeid=tblModel.getValueAt(tblema.getSelectedRow(),0).toString();
            String tblfirstname=tblModel.getValueAt(tblema.getSelectedRow(),1).toString();
            String tbllastname=tblModel.getValueAt(tblema.getSelectedRow(),2).toString();
            String tbldepartment=tblModel.getValueAt(tblema.getSelectedRow(),3).toString();
            String tbldesignation=tblModel.getValueAt(tblema.getSelectedRow(),4).toString();
            String tblgender=tblModel.getValueAt(tblema.getSelectedRow(),5).toString();
            String tblstatus=tblModel.getValueAt(tblema.getSelectedRow(),6).toString();
            String tblcontactno=tblModel.getValueAt(tblema.getSelectedRow(),7).toString();
            
            
            txtemployeeid.setText(tblempolyeeid);
            txtfirstname1.setText(tblfirstname);
            txtlastname.setText(tbllastname);
            txtdepartment1.setSelectedItem(tbldepartment);
            txtdesignation.setSelectedItem(tbldesignation);
            txtgender.setSelectedItem(tblgender);
            txtstatus1.setSelectedItem(tblstatus);
            txtcontactno.setText(tblcontactno);
    }//GEN-LAST:event_tblemaMouseClicked

    private void txtdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesignationActionPerformed

    private void txtempolyeeid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempolyeeid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempolyeeid1ActionPerformed

    private void txtempolyeeid1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtempolyeeid1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempolyeeid1KeyPressed

    private void txtfirstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1ActionPerformed

    private void txtfirstname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirstname1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstname1KeyPressed

    private void txtstatus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatus1ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        String addValue = txtnewdepartment.getText();
        String addValue1 = txtnewdesignation2.getText();

        txtdepartment1.addItem(addValue);
        txtdesignation.addItem(addValue1);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void txtdepartment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepartment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdepartment1ActionPerformed

    private void txtnewdesignation21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewdesignation21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewdesignation21ActionPerformed

    private void txtnewdesignation21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewdesignation21KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewdesignation21KeyPressed

    private void txtnewdepartment1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewdepartment1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewdepartment1KeyPressed

    private void txtnewdepartment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewdepartment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewdepartment1ActionPerformed

    private void txtemployeeidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemployeeidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeeidKeyPressed

    private void txtemployeeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemployeeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemployeeidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnback;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblema;
    private javax.swing.JTextField txtcontactno;
    private javax.swing.JComboBox<String> txtdepartment1;
    private javax.swing.JComboBox<String> txtdesignation;
    private javax.swing.JTextField txtemployeeid;
    private javax.swing.JTextField txtfirstname1;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtnewdepartment;
    private javax.swing.JTextField txtnewdesignation2;
    private javax.swing.JComboBox<String> txtstatus1;
    // End of variables declaration//GEN-END:variables
}
